application: dubnotes
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
  
- url: /script
  static_dir: script

- url: /clientapp.html
  static_files: clientapp.html
  upload: clientapp.html

- url: /json/list
  script: dubnotes.py

- url: /json/(.*?)
  script: dubnotes.py

- url: /authenticate
  script: dubnotes.py

- url: /(edit|delete)/(.*?)
  script: dubnotes.py

- url: /(notes|new)
  script: dubnotes.py




